### ISSUE TITLE
ユーザー名が30文字で耐えられるよう ... で省略する

### ISSUE THREAD

**Issue by akiogitgit** [akiogitgit/share-pos#166]
## 詳細
ユーザー名を30文字以下で入力するようにしたので、レイアウト崩れないようにする
- PostItem インデックスページ
- UserProfile ユーザーページ

UserCard.tsx参考に
```css
.text-overflow {
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
}
```
